from enum import Enum


class Language(Enum):
    MDA = {'name': 'Mada', 'script': 'Latin'}
    NIN = {'name': 'Ninzo', 'script': 'Latin'}
    ODU = {'name': 'Odual', 'script': 'Latin'}
    ABN = {'name': 'Abua', 'script': 'Latin'}
    EGO = {'name': 'Eggon', 'script': 'Latin'}
    KYQ = {'name': 'Kenga', 'script': 'Latin'}
    BDH = {'name': 'Baka', 'script': 'Latin'}
    EKA = {'name': 'Ekajuk', 'script': 'Latin'}
    BZA = {'name': 'Bandi', 'script': 'Latin'}
    BFA = {'name': 'Bari', 'script': 'Latin'}
    AHA = {'name': 'Ahanta', 'script': 'Latin'}
    BOX = {'name': 'Bwamu / Buamu', 'script': 'Latin'}
    WBI = {'name': 'Vwanji', 'script': 'Latin'}
    MWE = {'name': 'Mwera', 'script': 'Latin'}
    ASA = {'name': 'Asu', 'script': 'Latin'}
    BEM = {'name': 'Bemba / Chibemba', 'script': 'Latin'}
    BEQ = {'name': 'Beembe', 'script': 'Latin'}
    BEZ = {'name': 'Bena', 'script': 'Latin'}
    BXK = {'name': 'Bukusu', 'script': 'Latin'}
    CCE = {'name': 'Chopi', 'script': 'Latin'}
    CHW = {'name': 'Chuabo', 'script': 'Latin'}
    CJK = {'name': 'Chokwe', 'script': 'Latin'}
    CWE = {'name': 'Kwere', 'script': 'Latin'}
    DAV = {'name': 'Dawida / Taita', 'script': 'Latin'}
    DHM = {'name': 'Dhimba', 'script': 'Latin'}
    DIG = {'name': 'Chidigo', 'script': 'Latin'}
    DIU = {'name': 'Gciriku', 'script': 'Latin'}
    DUG = {'name': 'Chiduruma', 'script': 'Latin'}
    EBU = {'name': 'Kiembu / Embu', 'script': 'Latin'}
    EKO = {'name': 'Koti', 'script': 'Latin'}
    FIP = {'name': 'Fipa', 'script': 'Latin'}
    FLR = {'name': 'Fuliiru', 'script': 'Latin'}
    GOG = {'name': 'Gogo', 'script': 'Latin'}
    GUZ = {'name': 'Ekegusii', 'script': 'Latin'}
    GWR = {'name': 'Gwere', 'script': 'Latin'}
    HAY = {'name': 'Haya', 'script': 'Latin'}
    JIT = {'name': 'Jita', 'script': 'Latin'}
    JMC = {'name': 'Machame', 'script': 'Latin'}
    KAM = {'name': 'Kikamba', 'script': 'Latin'}
    KCK = {'name': 'Kalanga', 'script': 'Latin'}
    KDC = {'name': 'Kutu', 'script': 'Latin'}
    KDE = {'name': 'Makonde', 'script': 'Latin'}
    KDN = {'name': 'Kunda', 'script': 'Latin'}
    KIK = {'name': 'Gikuyu / Kikuyu', 'script': 'Latin'}
    KIN = {'name': 'Kinyarwanda', 'script': 'Latin'}
    KIZ = {'name': 'Kisi', 'script': 'Latin'}
    KKI = {'name': 'Kagulu', 'script': 'Latin'}
    KMB = {'name': 'Kimbundu', 'script': 'Latin'}
    KNG = {'name': 'Kongo', 'script': 'Latin'}
    KOO = {'name': 'Konzo', 'script': 'Latin'}
    KQN = {'name': 'Kikaonde', 'script': 'Latin'}
    KSB = {'name': 'Shambala / Kishambala', 'script': 'Latin'}
    KUA = {'name': 'Oshiwambo', 'script': 'Latin'}
    KUJ = {'name': 'Kuria', 'script': 'Latin'}
    KWN = {'name': 'Kwangali', 'script': 'Latin'}
    LAI = {'name': 'Lambya', 'script': 'Latin'}
    LAM = {'name': 'Lamba', 'script': 'Latin'}
    LGM = {'name': 'Lega-mwenga', 'script': 'Latin'}
    LIK = {'name': 'Lika', 'script': 'Latin'}
    MCK = {'name': 'Mbunda', 'script': 'Latin'}
    MER = {'name': 'Kimiiru', 'script': 'Latin'}
    MGH = {'name': 'Makhuwa-Meetto', 'script': 'Latin'}
    MGQ = {'name': 'Malila', 'script': 'Latin'}
    MGR = {'name': 'Mambwe-Lungu', 'script': 'Latin'}
    MGW = {'name': 'Matumbi', 'script': 'Latin'}
    MWS = {'name': 'Mwimbi-Muthambi', 'script': 'Latin'}
    MYX = {'name': 'Masaaba', 'script': 'Latin'}
    NBA = {'name': 'Nyemba', 'script': 'Latin'}
    NBL = {'name': 'IsiNdebele', 'script': 'Latin'}
    NDC = {'name': 'Ndau', 'script': 'Latin'}
    NDE = {'name': 'IsiNdebele', 'script': 'Latin'}
    NDH = {'name': 'Ndali', 'script': 'Latin'}
    NDJ = {'name': 'Ndamba', 'script': 'Latin'}
    NDO = {'name': 'Ndonga', 'script': 'Latin'}
    NGL = {'name': 'Lomwe', 'script': 'Latin'}
    NGO = {'name': 'Ngoni', 'script': 'Latin'}
    NGP = {'name': 'Ngulu', 'script': 'Latin'}
    NIH = {'name': 'Nyiha', 'script': 'Latin'}
    NIM = {'name': 'Nilamba / kinilyamba', 'script': 'Latin'}
    NKA = {'name': 'Nkoya / ShiNkoya', 'script': 'Latin'}
    NNQ = {'name': 'Ngindo', 'script': 'Latin'}
    NSE = {'name': 'Chinsenga', 'script': 'Latin'}
    NSO = {'name': 'Sepedi', 'script': 'Latin'}
    NUJ = {'name': 'Nyole', 'script': 'Latin'}
    NYA = {'name': 'Chichewa', 'script': 'Latin'}
    NYD = {'name': 'Olunyole / Nyore', 'script': 'Latin'}
    NYF = {'name': 'Giryama', 'script': 'Latin'}
    NYK = {'name': 'Nyaneka', 'script': 'Latin'}
    NYM = {'name': 'Nyamwezi', 'script': 'Latin'}
    NYN = {'name': 'Nyankore / Nyankole', 'script': 'Latin'}
    NYO = {'name': 'Nyoro', 'script': 'Latin'}
    NYU = {'name': 'Nyungwe', 'script': 'Latin'}
    NYY = {'name': 'Nyakyusa-Ngonde / Kyangonde', 'script': 'Latin'}
    POY = {'name': 'Pogolo / Shipogoro-Pogolo', 'script': 'Latin'}
    RAG = {'name': 'Lulogooli', 'script': 'Latin'}
    RIM = {'name': 'Nyaturu', 'script': 'Latin'}
    RND = {'name': 'Uruund', 'script': 'Latin'}
    RNG = {'name': 'Ronga / ShiRonga', 'script': 'Latin'}
    RUB = {'name': 'Gungu', 'script': 'Latin'}
    RUN = {'name': 'Rundi / Kirundi', 'script': 'Latin'}
    RWK = {'name': 'Rwa', 'script': 'Latin'}
    SBP = {'name': 'Sangu', 'script': 'Latin'}
    SBS = {'name': 'Kuhane', 'script': 'Latin'}
    SBY = {'name': 'Soli', 'script': 'Latin'}
    SNA = {'name': 'Shona', 'script': 'Latin'}
    SNG = {'name': 'Sanga / Kiluba', 'script': 'Latin'}
    SOP = {'name': 'Kisonge', 'script': 'Latin'}
    SOT = {'name': 'Sesotho', 'script': 'Latin'}
    SSW = {'name': 'Siswati', 'script': 'Latin'}
    SUK = {'name': 'Sukuma', 'script': 'Latin'}
    SWA = {'name': 'Swahili', 'script': 'Latin'}
    SWC = {'name': 'Swahili Congo', 'script': 'Latin'}
    SWH = {'name': 'Swahili', 'script': 'Latin'}
    SWK = {'name': 'Sena, Malawi', 'script': 'Latin'}
    SXB = {'name': 'Suba', 'script': 'Latin'}
    THK = {'name': 'Tharaka', 'script': 'Latin'}
    TKE = {'name': 'Takwane', 'script': 'Latin'}
    TLJ = {'name': 'Talinga-Bwisi', 'script': 'Latin'}
    TOG = {'name': 'Tonga', 'script': 'Latin'}
    TOH = {'name': 'Gitonga', 'script': 'Latin'}
    TOI = {'name': 'Chitonga', 'script': 'Latin'}
    TSC = {'name': 'Tshwa', 'script': 'Latin'}
    TSN = {'name': 'Setswana', 'script': 'Latin'}
    TSO = {'name': 'Tsonga', 'script': 'Latin'}
    TTJ = {'name': 'Toro / Rutoro', 'script': 'Latin'}
    TUM = {'name': 'Chitumbuka', 'script': 'Latin'}
    UMB = {'name': 'Umbundu', 'script': 'Latin'}
    VEN = {'name': 'Tshivenda', 'script': 'Latin'}
    VID = {'name': 'Chividunda', 'script': 'Latin'}
    VIF = {'name': 'Vili', 'script': 'Latin'}
    VMK = {'name': 'Makhuwa-Shirima', 'script': 'Latin'}
    VMW = {'name': 'Macua', 'script': 'Latin'}
    VUN = {'name': 'Kivunjo', 'script': 'Latin'}
    WMW = {'name': 'Mwani', 'script': 'Latin'}
    XHO = {'name': 'Isixhosa', 'script': 'Latin'}
    XOG = {'name': 'Soga', 'script': 'Latin'}
    YAO = {'name': 'Yao / Chiyao', 'script': 'Latin'}
    YOM = {'name': 'Ibinda', 'script': 'Latin'}
    ZAJ = {'name': 'Zaramo', 'script': 'Latin'}
    ZDJ = {'name': 'Comorian, Ngazidja', 'script': 'Latin'}
    ZGA = {'name': 'Kinga', 'script': 'Latin'}
    ZIW = {'name': 'Zigula', 'script': 'Latin'}
    ZUL = {'name': 'Isizulu', 'script': 'Latin'}
    MWN = {'name': 'Cinamwanga', 'script': 'Latin'}
    LOZ = {'name': 'Silozi', 'script': 'Latin'}
    LSM = {'name': 'Saamya-Gwe / Saamia', 'script': 'Latin'}
    LTO = {'name': 'Tsotso', 'script': 'Latin'}
    LUA = {'name': 'Tshiluba', 'script': 'Latin'}
    LUE = {'name': 'Luvale', 'script': 'Latin'}
    LUG = {'name': 'Luganda', 'script': 'Latin'}
    LUN = {'name': 'Lunda', 'script': 'Latin'}
    LWG = {'name': 'Wanga', 'script': 'Latin'}
    DWR = {'name': 'Dawro', 'script': 'Latin'}
    GMV = {'name': 'Gamo', 'script': 'Latin'}
    GOF = {'name': 'Goofa', 'script': 'Latin'}
    WAL = {'name': 'Wolaytta', 'script': 'Latin'}
    BCI = {'name': 'Baoulé', 'script': 'Latin'}
    CKO = {'name': 'Anufo', 'script': 'Latin'}
    FAT = {'name': 'Fante', 'script': 'Latin'}
    NZI = {'name': 'Nzema', 'script': 'Latin'}
    SFW = {'name': 'Sehwi', 'script': 'Latin'}
    TWI = {'name': 'Twi', 'script': 'Latin'}
    HEH = {'name': 'Hehe', 'script': 'Latin'}
    HER = {'name': 'Herero', 'script': 'Latin'}
    PEM = {'name': 'Kipende', 'script': 'Latin'}
    PKB = {'name': 'Kipfokomo / Pokomo', 'script': 'Latin'}
    DIB = {'name': 'Dinka, South Central', 'script': 'Latin'}
    DIK = {'name': 'Dinka, Southwestern', 'script': 'Latin'}
    DIP = {'name': 'Dinka, Northeastern', 'script': 'Latin'}
    DKS = {'name': 'Dinka, Southeastern', 'script': 'Latin'}
    NUS = {'name': 'Nuer', 'script': 'Latin'}
    DOW = {'name': 'Doyayo', 'script': 'Latin'}
    KMY = {'name': 'Koma', 'script': 'Latin'}
    GKN = {'name': 'Gokana', 'script': 'Latin'}
    OGO = {'name': 'Khana', 'script': 'Latin'}
    KQY = {'name': 'Koorete', 'script': 'Latin'}
    FUH = {'name': 'Fulfulde, Western Niger', 'script': 'Latin'}
    FUQ = {'name': 'Fulfulde Central Eastern Niger', 'script': 'Latin'}
    FUV = {'name': 'Fulfulde Nigeria', 'script': 'Arabic'}
    FUB = {'name': 'Fulfulde, Adamawa', 'script': 'Latin'}
    GNA = {'name': 'Kaansa', 'script': 'Latin'}
    KBP = {'name': 'Kabiye', 'script': 'Latin'}
    KDH = {'name': 'Tem', 'script': 'Latin'}
    LEE = {'name': 'Lyélé', 'script': 'Latin'}
    MZW = {'name': 'Deg', 'script': 'Latin'}
    NNW = {'name': 'Nuni, Southern', 'script': 'Latin'}
    NTR = {'name': 'Delo', 'script': 'Latin'}
    SIG = {'name': 'Paasaal', 'script': 'Latin'}
    SIL = {'name': 'Sisaala, Tumulung', 'script': 'Latin'}
    TPM = {'name': 'Tampulma', 'script': 'Latin'}
    XSM = {'name': 'Kasem', 'script': 'Latin'}
    VAG = {'name': 'Vagla', 'script': 'Latin'}
    ACD = {'name': 'Gikyode', 'script': 'Latin'}
    NAW = {'name': 'Nawuri', 'script': 'Latin'}
    NCU = {'name': 'Chunburung', 'script': 'Latin'}
    NKO = {'name': 'Nkonya', 'script': 'Latin'}
    IDU = {'name': 'Idoma', 'script': 'Latin'}
    IGE = {'name': 'Igede', 'script': 'Latin'}
    YBA = {'name': 'Yala', 'script': 'Latin'}
    BQJ = {'name': 'Bandial', 'script': 'Latin'}
    CSK = {'name': 'Jola Kasa', 'script': 'Latin'}
    JIB = {'name': 'Jibu', 'script': 'Latin'}
    NNB = {'name': 'Nande / Ndandi', 'script': 'Latin'}
    KLN = {'name': 'Kalenjin', 'script': 'Latin'}
    PKO = {'name': 'Pökoot', 'script': 'Latin'}
    KRX = {'name': 'Karon', 'script': 'Latin'}
    KIA = {'name': 'Kim', 'script': 'Latin'}
    CME = {'name': 'Cerma', 'script': 'Latin'}
    AKP = {'name': 'Siwu', 'script': 'Latin'}
    LEF = {'name': 'Lelemi', 'script': 'Latin'}
    LIP = {'name': 'Sekpele', 'script': 'Latin'}
    SNW = {'name': 'Selee', 'script': 'Latin'}
    KDJ = {'name': 'Ng’akarimojong', 'script': 'Latin'}
    LOT = {'name': 'Latuka', 'script': 'Latin'}
    MAS = {'name': 'Maasai', 'script': 'Latin'}
    SAQ = {'name': 'Samburu', 'script': 'Latin'}
    TEO = {'name': 'Teso', 'script': 'Latin'}
    TUV = {'name': 'Turkana', 'script': 'Latin'}
    ADH = {'name': 'Jopadhola / Adhola', 'script': 'Latin'}
    ALZ = {'name': 'Alur', 'script': 'Latin'}
    ANU = {'name': 'Anyuak / Anuak', 'script': 'Latin'}
    KDI = {'name': 'Kumam', 'script': 'Latin'}
    LAJ = {'name': 'Lango', 'script': 'Latin'}
    LTH = {'name': 'Thur / Acholi-Labwor', 'script': 'Latin'}
    luo = {'name': 'Dholuo / Luo', 'script': 'Latin'} 
    lwo = {'name': 'Luwo', 'script': 'Latin'} 
    mfz = {'name': 'Mabaan', 'script': 'Latin'} 
    shk = {'name': 'Shilluk', 'script': 'Latin'} 
    ach = {'name': 'Acholi', 'script': 'Latin'} 
    mpe = {'name': 'Majang', 'script': 'Latin'} 
    mcu = {'name': 'Mambila, Cameroon', 'script': 'Latin'} 
    bam = {'name': 'Bambara', 'script': 'Latin'} 
    dyu = {'name': 'Jula', 'script': 'Latin'} 
    knk = {'name': 'Kuranko', 'script': 'Latin'} 
    msc = {'name': 'Maninka, Sankaran', 'script': 'Latin'} 
    mfg = {'name': 'Mogofin', 'script': 'Latin'} 
    mnk = {'name': 'Mandinka', 'script': 'Latin'} 
    nza = {'name': 'Mbembe, Tigon', 'script': 'Latin'} 
    kbn = {'name': 'Kare', 'script': 'Latin'} 
    kzr = {'name': 'Karang', 'script': 'Latin'} 
    tui = {'name': 'Toupouri', 'script': 'Latin'} 
    xuo = {'name': 'Kuo', 'script': 'Latin'} 
    men = {'name': 'Mende', 'script': 'Latin'} 
    bex = {'name': 'Jur Modo', 'script': 'Latin'} 
    mgc = {'name': 'Morokodo', 'script': 'Latin'} 
    bcn = {'name': 'Bali', 'script': 'Latin'} 
    mzm = {'name': 'Mumuye', 'script': 'Latin'} 
    agq = {'name': 'Aghem', 'script': 'Latin'} 
    azo = {'name': 'Awing', 'script': 'Latin'} 
    bav = {'name': 'Vengo', 'script': 'Latin'} 
    bbj = {'name': "Ghomálá'", 'script': 'Latin'} 
    bbk = {'name': 'Babanki', 'script': 'Latin'} 
    bfd = {'name': 'Bafut', 'script': 'Latin'} 
    bmo = {'name': 'Bambalang', 'script': 'Latin'} 
    bmv = {'name': 'Bum', 'script': 'Latin'} 
    byv = {'name': 'Medumba', 'script': 'Latin'} 
    jgo = {'name': 'Ngomba', 'script': 'Latin'} 
    lmp = {'name': 'Limbum', 'script': 'Latin'} 
    mgo = {'name': "Meta'", 'script': 'Latin'} 
    mnf = {'name': 'Mundani', 'script': 'Latin'} 
    ngn = {'name': 'Bassa', 'script': 'Latin'} 
    nla = {'name': 'Ngombale', 'script': 'Latin'} 
    nnh = {'name': 'Ngiemboon', 'script': 'Latin'} 
    oku = {'name': 'Oku', 'script': 'Latin'} 
    yam = {'name': 'Yamba', 'script': 'Latin'} 
    ybb = {'name': 'Yemba', 'script': 'Latin'} 
    mdm = {'name': 'Mayogo', 'script': 'Latin'} 
    mbu = {'name': 'Mbula-Bwazza', 'script': 'Latin'} 
    gjn = {'name': 'Gonja', 'script': 'Latin'} 
    buy = {'name': 'Bullom So', 'script': 'Latin'} 
    gya = {'name': 'Gbaya, Northwest', 'script': 'Latin'} 
    bss = {'name': 'Akoose', 'script': 'Latin'} 
    bum = {'name': 'Bulu', 'script': 'Latin'} 
    dua = {'name': 'Douala', 'script': 'Latin'} 
    eto = {'name': 'Eton', 'script': 'Latin'} 
    ewo = {'name': 'Ewondo', 'script': 'Latin'} 
    iyx = {'name': 'yaka', 'script': 'Latin'} 
    khy = {'name': 'Kele / Lokele', 'script': 'Latin'} 
    kkj = {'name': 'Kako', 'script': 'Latin'} 
    koq = {'name': 'Kota', 'script': 'Latin'} 
    ksf = {'name': 'Bafia', 'script': 'Latin'} 
    lin = {'name': 'Lingala', 'script': 'Latin'} 
    mcp = {'name': 'Makaa', 'script': 'Latin'} 
    ngc = {'name': 'Ngombe', 'script': 'Latin'} 
    nxd = {'name': 'Ngando', 'script': 'Latin'} 
    ozm = {'name': 'Koonzime', 'script': 'Latin'} 
    tll = {'name': 'Otetela', 'script': 'Latin'} 
    tvu = {'name': 'Tunen', 'script': 'Latin'} 
    won = {'name': 'Wongo', 'script': 'Latin'} 
    yat = {'name': 'Yambeta', 'script': 'Latin'} 
    lem = {'name': 'Nomaande', 'script': 'Latin'} 
    loq = {'name': 'Lobala', 'script': 'Latin'} 
    ibb = {'name': 'Ibibio', 'script': 'Latin'} 
    efi = {'name': 'Efik', 'script': 'Latin'} 
    ann = {'name': 'Obolo', 'script': 'Latin'} 
    bfo = {'name': 'Birifor, Malba', 'script': 'Latin'} 
    bim = {'name': 'Bimoba', 'script': 'Latin'} 
    biv = {'name': 'Birifor, Southern', 'script': 'Latin'} 
    bud = {'name': 'Ntcham', 'script': 'Latin'} 
    bwu = {'name': 'Buli', 'script': 'Latin'} 
    dag = {'name': 'Dagbani', 'script': 'Latin'} 
    dga = {'name': 'Dagaare', 'script': 'Latin'} 
    dgd = {'name': 'Dagaari Dioula', 'script': 'Latin'} 
    dgi = {'name': 'Dagara, Northern', 'script': 'Latin'} 
    gng = {'name': 'Ngangam', 'script': 'Latin'} 
    gur = {'name': 'Farefare', 'script': 'Latin'} 
    gux = {'name': 'Gourmanchema', 'script': 'Latin'} 
    hag = {'name': 'Hanga', 'script': 'Latin'} 
    kma = {'name': 'Konni', 'script': 'Latin'} 
    kus = {'name': 'Kusaal', 'script': 'Latin'} 
    maw = {'name': 'Mampruli', 'script': 'Latin'} 
    mfq = {'name': 'Moba', 'script': 'Latin'} 
    mos = {'name': 'Moore', 'script': 'Latin'} 
    soy = {'name': 'Miyobe', 'script': 'Latin'} 
    xon = {'name': 'Konkomba', 'script': 'Latin'} 
    mwm = {'name': 'Sar', 'script': 'Latin'} 
    myb = {'name': 'Mbay', 'script': 'Latin'} 
    bjv = {'name': 'Bedjond', 'script': 'Latin'} 
    gqr = {'name': 'Gor', 'script': 'Latin'} 
    gvl = {'name': 'Gulay', 'script': 'Latin'} 
    ksp = {'name': 'Kabba', 'script': 'Latin'} 
    lap = {'name': 'Laka', 'script': 'Latin'} 
    sba = {'name': 'Ngambay', 'script': 'Latin'} 
    ndz = {'name': 'Ndogo', 'script': 'Latin'} 
    lnl = {'name': 'Banda, South Central', 'script': 'Latin'} 
    bun = {'name': 'Sherbro', 'script': 'Latin'} 
    gso = {'name': 'Gbaya, Southwest', 'script': 'Latin'} 
    mur = {'name': 'Murle', 'script': 'Latin'} 
    did = {'name': 'Didinga', 'script': 'Latin'} 
    tex = {'name': 'Tennet', 'script': 'Latin'} 
    vut = {'name': 'Vute', 'script': 'Latin'} 
    tcc = {'name': 'Datooga', 'script': 'Latin'} 
    kno = {'name': 'Kono', 'script': 'Latin'} 
    vai = {'name': 'Vai', 'script': 'Vai'} 
    tul = {'name': 'Kutule', 'script': 'Latin'} 
    bst = {'name': 'Basketo', 'script': 'Ethiopic'} 
    ffm = {'name': 'Fulfulde, Maasina', 'script': 'Latin'} 
    fue = {'name': 'Fulfulde, Borgu', 'script': 'Latin'} 
    fuf = {'name': 'Pular', 'script': 'Latin'} 
    zne = {'name': 'Zande / paZande', 'script': 'Latin'} 
    guw = {'name': 'Gun', 'script': 'Latin'} 
    amh = {'name': 'Amharic', 'script': 'Ethiopic'} 
    bsp = {'name': 'Baga Sitemu', 'script': 'Latin'} 
    bzw = {'name': 'Basa', 'script': 'Latin'} 
    nhu = {'name': 'Noone', 'script': 'Latin'} 
    avu = {'name': 'Avokaya', 'script': 'Latin'} 
    kbo = {'name': 'Keliko', 'script': 'Latin'} 
    lgg = {'name': 'Lugbara', 'script': 'Latin'} 
    log = {'name': 'Logo', 'script': 'Latin'} 
    luc = {'name': 'Aringa', 'script': 'Latin'} 
    xnz = {'name': 'Mattokki', 'script': 'Latin'} 
    uth = {'name': 'u̱t-Hun', 'script': 'Latin'} 
    kyf = {'name': 'Kouya', 'script': 'Latin'} 
    ijn = {'name': 'Kalabari', 'script': 'Latin'} 
    okr = {'name': 'Kirike', 'script': 'Latin'} 
    shj = {'name': 'Shatt', 'script': 'Latin'} 
    lro = {'name': 'Laro', 'script': 'Latin'} 
    mkl = {'name': 'Mokole', 'script': 'Latin'} 
    yor = {'name': 'Yoruba', 'script': 'Latin'} 
    bin = {'name': 'Edo', 'script': 'Latin'} 
    ish = {'name': 'Esan', 'script': 'Latin'} 
    etu = {'name': 'Ejagham', 'script': 'Latin'} 
    fon = {'name': 'Fon', 'script': 'Latin'} 
    ful = {'name': 'Fulah', 'script': 'Latin'} 
    gbr = {'name': 'Gbagyi', 'script': 'Latin'} 
    atg = {'name': 'Ivbie North-Okpela-Arhe', 'script': 'Latin'} 
    krw = {'name': 'Krahn, Western', 'script': 'Latin'} 
    wec = {'name': 'Guéré', 'script': 'Latin'} 
    har = {'name': 'Harari', 'script': 'Latin'} 
    igl = {'name': 'Igala', 'script': 'Latin'} 
    ktj = {'name': 'Krumen, Plapo', 'script': 'Latin'} 
    ted = {'name': 'Krumen, Tepo', 'script': 'Latin'} 
    asg = {'name': 'Cishingini', 'script': 'Latin'} 
    kdl = {'name': 'Tsikimba', 'script': 'Latin'} 
    tsw = {'name': 'Tsishingini', 'script': 'Latin'} 
    xrb = {'name': 'Karaboro, Eastern', 'script': 'Latin'} 
    kqs = {'name': 'Kisi', 'script': 'Latin'} 
    gbo = {'name': 'Grebo, Northern', 'script': 'Latin'} 
    lom = {'name': 'Loma', 'script': 'Latin'} 
    anv = {'name': 'Denya', 'script': 'Latin'} 
    ken = {'name': 'Kenyang', 'script': 'Latin'} 
    mfi = {'name': 'Wandala', 'script': 'Latin'} 
    mev = {'name': 'Maan / Mann', 'script': 'Latin'} 
    ngb = {'name': 'Ngbandi, Northern', 'script': 'Latin'} 
    fia = {'name': 'Nobiin', 'script': 'Latin'} 
    nwb = {'name': 'Nyabwa', 'script': 'Latin'} 
    mdy = {'name': 'Maale', 'script': 'Ethiopic'} 
    ebr = {'name': 'Ebrié', 'script': 'Latin'} 
    sef = {'name': 'Sénoufo, Cebaara', 'script': 'Latin'} 
    iri = {'name': 'Rigwe', 'script': 'Latin'} 
    izr = {'name': 'Izere', 'script': 'Latin'} 
    kcg = {'name': 'Tyap', 'script': 'Latin'} 
    spp = {'name': 'Sénoufo, Supyire', 'script': 'Latin'} 
    myk = {'name': 'Sénoufo, Mamara', 'script': 'Latin'} 
    dyi = {'name': 'Sénoufo, Djimini', 'script': 'Latin'} 
    sev = {'name': 'Sénoufo, Nyarafolo', 'script': 'Latin'} 
    tgw = {'name': 'Sénoufo, Tagwana', 'script': 'Latin'} 
    tem = {'name': 'Timne', 'script': 'Latin'} 
    tiv = {'name': 'Tiv', 'script': 'Latin'} 
    sgw = {'name': 'Sebat Bet Gurage', 'script': 'Latin'} 
    dnj = {'name': 'Dan', 'script': 'Latin'} 
    wol = {'name': 'Wolof', 'script': 'Latin'} 
    fak = {'name': 'Fang', 'script': 'Latin'} 
    sor = {'name': 'Somrai', 'script': 'Latin'} 
    bwr = {'name': 'Bura Pabir', 'script': 'Latin'} 
    kqp = {'name': 'Kimré', 'script': 'Latin'} 
    daa = {'name': 'Dangaléat', 'script': 'Latin'} 
    mmy = {'name': 'Migaama', 'script': 'Latin'} 
    hbb = {'name': 'Nya huba', 'script': 'Latin'} 
    aba = {'name': 'Abé / Abbey', 'script': 'Latin'} 
    adj = {'name': 'Adjukru  / Adioukrou', 'script': 'Latin'} 
    ati = {'name': 'Attié', 'script': 'Latin'} 
    avn = {'name': 'Avatime', 'script': 'Latin'} 
    nyb = {'name': 'Nyangbo', 'script': 'Latin'} 
    tcd = {'name': 'Tafi', 'script': 'Latin'} 
    bba = {'name': 'Baatonum', 'script': 'Latin'} 
    bky = {'name': 'Bokyi', 'script': 'Latin'} 
    bom = {'name': 'Berom', 'script': 'Latin'} 
    etx = {'name': 'Iten / Eten', 'script': 'Latin'} 
    gud = {'name': 'Dida, Yocoboué', 'script': 'Latin'} 
    igb = {'name': 'Ebira', 'script': 'Latin'} 
    ada = {'name': 'Dangme', 'script': 'Latin'} 
    gaa = {'name': 'Ga', 'script': 'Latin'} 
    ewe = {'name': 'Éwé', 'script': 'Latin'} 
    gol = {'name': 'Gola', 'script': 'Latin'} 
    yre = {'name': 'Yaouré', 'script': 'Latin'} 
    ibo = {'name': 'Igbo', 'script': 'Latin'} 
    ikk = {'name': 'Ika', 'script': 'Latin'} 
    ikw = {'name': 'Ikwere', 'script': 'Latin'} 
    iqw = {'name': 'Ikwo', 'script': 'Latin'} 
    izz = {'name': 'Izii', 'script': 'Latin'} 
    klu = {'name': 'Klao', 'script': 'Latin'} 
    gkp = {'name': 'Kpelle, Guinea', 'script': 'Latin'} 
    xpe = {'name': 'Kpelle', 'script': 'Latin'} 
    bov = {'name': 'Tuwuli', 'script': 'Latin'} 
    ajg = {'name': 'Aja', 'script': 'Latin'} 
    krs = {'name': 'Gbaya', 'script': 'Latin'} 
    xed = {'name': 'Hdi', 'script': 'Latin'} 
    niy = {'name': 'Ngiti', 'script': 'Latin'} 
    afr = {'name': 'Afrikaans', 'script': 'Latin'} 
    knf = {'name': 'Mankanya', 'script': 'Latin'} 
    moy = {'name': 'Shekkacho', 'script': 'Latin'} 
    iso = {'name': 'Isoko', 'script': 'Latin'} 
    oke = {'name': 'Okpe', 'script': 'Latin'} 
    urh = {'name': 'Urhobo', 'script': 'Latin'} 
    sus = {'name': 'Sosoxui', 'script': 'Latin'} 
    yal = {'name': 'Yalunka', 'script': 'Latin'} 
    bsc = {'name': 'Oniyan', 'script': 'Latin'} 
    cou = {'name': 'Wamey', 'script': 'Latin'}
    wib = {'name': 'Toussian, Southern', 'script': 'Latin'}
    moa = {'name': 'Mwan', 'script': 'Latin'}
    ttr = {'name': 'Nyimatli', 'script': 'Latin'}
    kub = {'name': 'Kutep', 'script': 'Latin'}
    hau = {'name': 'Hausa', 'script': 'Latin'}
    bcw = {'name': 'Bana', 'script': 'Latin'}
    kvj = {'name': 'Psikye', 'script': 'Latin'}
    giz = {'name': 'South Giziga', 'script': 'Latin'}
    gnd = {'name': 'Zulgo-gemzek', 'script': 'Latin'}
    maf = {'name': 'Mafa', 'script': 'Latin'}
    meq = {'name': 'Merey', 'script': 'Latin'}
    mfh = {'name': 'Matal', 'script': 'Latin'}
    mfk = {'name': 'Mofu, North', 'script': 'Latin'}
    mif = {'name': 'Mofu-Gudur', 'script': 'Latin'}
    mlr = {'name': 'Vame', 'script': 'Latin'}
    mqb = {'name': 'Mbuko', 'script': 'Latin'}
    muy = {'name': 'Muyang', 'script': 'Latin'}
    hna = {'name': 'Mina', 'script': 'Latin'}
    bcy = {'name': 'Bacama', 'script': 'Latin'}
    gde = {'name': 'Gude', 'script': 'Latin'}
    moz = {'name': 'Mukulu', 'script': 'Latin'}
    bib = {'name': 'Bisa', 'script': 'Latin'}
    bqc = {'name': 'Boko', 'script': 'Latin'}
    bus = {'name': 'Bokobaru', 'script': 'Latin'}
    ndv = {'name': 'Ndut', 'script': 'Latin'}
    snf = {'name': 'Noon', 'script': 'Latin'}
    byf = {'name': 'Bété', 'script': 'Latin'}
    lia = {'name': 'Limba, West-Central', 'script': 'Latin'}
    mlg = {'name': 'Malagasy', 'script': 'Latin'}
    tir = {'name': 'Tigrinya', 'script': 'Ethiopic'}
    rif = {'name': 'Tarifit', 'script': 'Arabic'}
    sbd = {'name': 'Samo, Southern', 'script': 'Latin'}
    nhr = {'name': 'Naro', 'script': 'Latin'}
    lmd = {'name': 'Lumun', 'script': 'Latin'}
    shi = {'name': 'Tachelhit', 'script': 'Latin'}
    gid = {'name': 'Gidar', 'script': 'Latin'}
    xan = {'name': 'Xamtanga', 'script': 'Ethiopic'}
    hgm = {'name': 'Hai|ǁom', 'script': 'Latin'}
    sid = {'name': 'Sidama', 'script': 'Latin'}
    kab = {'name': 'Kabyle', 'script': 'Latin'}
    xtc = {'name': 'Katcha-Kadugli-Miri', 'script': 'Latin'}
    kby = {'name': 'Kanuri, Manga', 'script': 'Latin'}
    kri = {'name': 'Krio', 'script': 'Latin'}
    wes = {'name': 'Pidgin, Cameroon', 'script': 'Latin'}
    pcm = {'name': 'Nigerian Pidgin', 'script': 'Latin'}
    naq = {'name': 'Khoekhoe', 'script': 'Latin'}
    thv = {'name': 'Tamahaq, Tahaggart', 'script': 'Latin'}
    gax = {'name': 'Oromo, Borana-Arsi-Guji', 'script': 'Ethiopic / Latin'}
    gaz = {'name': 'Oromo, West Central', 'script': 'Ethiopic / Latin'}
    orm = {'name': 'Oromo', 'script': 'Ethiopic / Latin'}
    rel = {'name': 'Rendille', 'script': 'Latin'}
    aar = {'name': 'Afar / Qafar', 'script': 'Latin'}
    som = {'name': 'Somali', 'script': 'Latin'}
    taq = {'name': 'Tamasheq', 'script': 'Latin'}
    ttq = {'name': 'Tawallammat', 'script': 'Latin'}
    dsh = {'name': 'Daasanach', 'script': 'Latin'}
    mcn = {'name': 'Masana / Massana', 'script': 'Latin'}
    mpg = {'name': 'Marba', 'script': 'Latin'}
    bds = {'name': 'Burunge', 'script': 'Latin'}
    ses = {'name': 'Songhay, Koyraboro Senni', 'script': 'Latin'}
    cop = {'name': 'Coptic', 'script': 'Coptic'}
    ber = {'name': 'Berber', 'script': 'Latin'}
    crs = {'name': 'Seychelles Creole', 'script': 'Latin'}
    mfe = {'name': 'Morisyen / Mauritian Creole', 'script': 'Latin'}
    ktu = {'name': 'Kikongo', 'script': 'Latin'}
    sag = {'name': 'Sango', 'script': 'Latin'}
    kea = {'name': 'Kabuverdianu', 'script': 'Latin'}
    pov = {'name': 'Guinea-Bissau Creole', 'script': 'Latin'}


class LanguageInfo:
    info = Language
    def __init__(self, label_file: str):
        with open(label_file, "r") as f:
            self.idx2code = {
                idx+4: code.split()[0]
                for idx, code in enumerate(f.readlines())
            }
    
    def get_language_info_from_idx(self, idx: int) -> dict[str, str]:
        return self.info[self.idx2code[idx].upper()].value
